apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: akalmand
  name: akalmand-deployment
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: akalmand
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: akalmand
    spec:
      containers:
        - name: akalmand
          image: registry.digitalocean.com/mufti-api/akalmand
          imagePullPolicy: Always
          env:
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  key: MONGODB_URL
                  name: study-app-environment-variables
            - name: MATHPIX_API_KEY
              valueFrom:
                secretKeyRef:
                  key: MATHPIX_API_KEY
                  name: study-app-environment-variables
            - name: MATHPIX_APPID
              valueFrom:
                secretKeyRef:
                  key: MATHPIX_APPID
                  name: study-app-environment-variables
            - name: OPENAI_APIKEY
              valueFrom:
                secretKeyRef:
                  key: OPENAI_APIKEY
                  name: study-app-environment-variables
            - name: DATABASE_NAME
              value: study-app
            - name: QDRANT_URL
              value: http://qdrant-study.default.svc.cluster.local:6333
            - name: UNSTRUCTURED_URL
              value: http://unstructured-study-service.default.svc.cluster.local:8000/general/v0/general
            - name: MAIN_URL_EXECUTOR
              value: http://code-runner-service.default.svc.cluster.local:8000/
            - name: EVALUATE_URL_EXECUTOR
              value: http://code-runner-service.default.svc.cluster.local:8000/evaluate
            - name: AVAILABLE_LIBRARIES_URL
              value: http://code-runner-service.default.svc.cluster.local:8000/allowed_libraries
            - name: REDIS_URL
              value: redis://redis-stack-service.default.svc.cluster.local:6379
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
