name: Deploy to DigitalOcean Kubernetes
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@main

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Generate unique tag
        id: uniquetag
        run: echo "IMAGE_TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Build container image
        run: docker build -t registry.digitalocean.com/mufti-api/akalmand:${{ env.IMAGE_TAG }} .

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 3000

      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/mufti-api/akalmand:${{ env.IMAGE_TAG }}

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 k8s-1-27-2-do-0-blr1-1686477516392

      - name: Deploy to DigitalOcean Kubernetes
        run: |
          kubectl set image deployment/akalmand-deployment akalmand=registry.digitalocean.com/mufti-api/akalmand:${{ env.IMAGE_TAG }} -n default
          kubectl rollout status deployment/akalmand-deployment -n default --timeout=600s

      - name: Verify deployment
        run: kubectl rollout status deployment/akalmand-deployment -n default
